version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-goseed
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: goseed
      POSTGRES_DB: goseed
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql-goseed
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: goseed
      MYSQL_DATABASE: goseed
      MYSQL_USER: goseed
      MYSQL_PASSWORD: goseed
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  postgres-data:
  mysql-data:
