version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: goseed
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: goseed
      POSTGRES_DB: goseed
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
